### PR TITLE
Added potions for health, damage, speed, and slow

### PR DESCRIPTION
**Pull request by allisonjoycarter**
Speed and slow currently do not work as there is no way to implement them. It would require a way to modify the movement of Person. The health and trap potions work. Also created a header file for Collectibles. Each potion has its own class file.

- Orange Potion: Gain 50 health
- Yellow Potion: Deal 20 damage
- Green Potion: 120% Speed for 5 seconds
- Blue Potion: 80% Speed for 5 seconds

### CODE REVIEW

**Comment by irawoodring** [comment]
I like it.
Did you talk to the Person team to see about changing speeds?

**Comment by irawoodring** [comment]
I like the code.  Have you had a chance to talk to the Person team yet?

**Comment by allisonjoycarter** [comment]
We did and they said they were planning on implementing methods to help with it, but haven't so far. We figured we would push what we have and do our best to keep updated on the status of those methods so hopefully we can fix it tomorrow

**Comment by irawoodring** [comment]
Sounds good, looks good!

**Comment by irawoodring** [comment]
👍

**Pull request merged**
